baseurl = "http://robertkluin.github.io"
title = "Core Dumps of a Biocomputer"
languageCode = "en-us"

[permalinks]
  post = "/:year/:month/:title/"

[params]
  Description = "Random crap from one biocomputer to another"
  Author = "Robert Kluin"
  github = "robertkluin"
  twitter = "robertkluin"
  SidebarRecentLimit = 5
